### PR TITLE
Closes #103 increase test coverage for quo r@devel

### LINKED ISSUE #103: General Issue: Increase test coverage for `quo.R`
### Background Information

We need to increase test coverage for our functions. The below screenshot has the function and gap in test coverage that we need to write additional unit tests. 

image

### Definition of Done

New tests written that covers the red gap area for is.R.

Use devtools::test_coverage() to reproduce the report

### PR DESCRIPTION
**Pull request by zdz2101**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page.
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging.
- [x] Address all merge conflicts and resolve appropriately.
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!
image
image

### CODE REVIEW

File: tests/testthat/test-quo.R [hunk 1]
```diff
@@ -1,25 +1,81 @@
...
     x <- rlang::enquo(x)
     assertthat::assert_that(quo_not_missing(x))
   }
   expect_true(test_fun(my_variable))
 })
 
-## Test 2: `quo_not_missing` throws and Error if missing argument ----
-test_that("quo_not_missing Test 2: `quo_not_missing` throws and Error if missing argument", {
+## Test 4: `quo_not_missing` throws and Error if missing argument ----
+test_that("quo_not_missing Test 4: `quo_not_missing` throws and Error if missing argument", {
```
Comment (bms63) [inline tests/testthat/test-quo.R:37]:
```suggestion
test_that("quo_not_missing Test 4: `quo_not_missing` throws an Error if missing argument", {
```

File: tests/testthat/test-quo.R [hunk 2]
```diff
@@ -1,25 +1,81 @@
...
   test_fun <- function(x) {
     x <- rlang::enquo(x)
     assertthat::assert_that(quo_not_missing(x))
   }
   expect_true(test_fun(my_variable))
 })
 
-## Test 2: `quo_not_missing` throws and Error if missing argument ----
-test_that("quo_not_missing Test 2: `quo_not_missing` throws and Error if missing argument", {
+## Test 4: `quo_not_missing` throws and Error if missing argument ----
```
Comment (bms63) [inline tests/testthat/test-quo.R:36]:
```suggestion
## Test 4: `quo_not_missing` throws an Error if missing argument ----
```

File: tests/testthat/test-quo.R [hunk 3]
```diff
@@ -1,25 +1,81 @@
...
+})
+
 # quo_not_missing ----
-## Test 1: `quo_not_missing` returns TRUE if no missing argument ----
-test_that("quo_not_missing Test 1: `quo_not_missing` returns TRUE if no missing argument", {
+## Test 3: `quo_not_missing` returns TRUE if no missing argument ----
+test_that("quo_not_missing Test 3: `quo_not_missing` returns TRUE if no missing argument", {
   test_fun <- function(x) {
     x <- rlang::enquo(x)
     assertthat::assert_that(quo_not_missing(x))
```
Comment (bms63) [inline tests/testthat/test-quo.R:31]: I think these are pacakge imports and don't need `pkgname::`  only packages with suggests like tibble.  Can you remove please if you agree

File: tests/testthat/test-quo.R [hunk 4]
```diff
@@ -1,25 +1,81 @@
...
   expect_true(test_fun(my_variable))
 })
 
-## Test 2: `quo_not_missing` throws and Error if missing argument ----
-test_that("quo_not_missing Test 2: `quo_not_missing` throws and Error if missing argument", {
+## Test 4: `quo_not_missing` throws and Error if missing argument ----
+test_that("quo_not_missing Test 4: `quo_not_missing` throws and Error if missing argument", {
   test_fun <- function(x) {
     x <- rlang::enquo(x)
     assertthat::assert_that(quo_not_missing(x))
```
Comment (bms63) [inline tests/testthat/test-quo.R:40]: I think these are pacakge imports and don't need `pkgname::`  only packages with suggests like tibble.  Can you remove please if you agree

File: tests/testthat/test-quo.R [hunk 5]
```diff
@@ -1,25 +1,81 @@
...
+  )
+  expect_equal(
+    expected = quo(STUDYID),
+    object = quo_c(x, NULL, y)[[2]]
+  )
+})
+
+## Test 2: `quo_c` returns error if non-quosures are input ----
+test_that("quo_c Test 2: `quo_c` returns error if non-quosures are input", {
+  USUBJID <- "01-701-1015" # nolint
```
Comment (bms63) [inline tests/testthat/test-quo.R:19]: how come this needs a nolint?

**Review by bms63 — CHANGES_REQUESTED** [review]
Thanks Zelos!  Please see above

File: tests/testthat/test-quo.R (hunk 5 above)
Comment (zdz2101) [reply tests/testthat/test-quo.R:19]: I was getting this:
image 
I suppose I can just change it to avoid the nolint, my thought in using the capitalized format was to somewhat mimic the usual SDTM/ADaM data clinical trial programmers run into

Comment (bms63) [reply tests/testthat/test-quo.R:19]: ah i see no problem if you want to keep as is

File: tests/testthat/test-quo.R (hunk 4 above)
Comment (zdz2101) [reply tests/testthat/test-quo.R:40]: That makes sense, it does indeed still run with the removal. Shall we revisit #130 too and add a snippet to discern the difference?

Comment (zdz2101) [reply tests/testthat/test-quo.R]: I personally wasn't aware of the`imports`/`suggests` difference but it made sense pretty quickly. So for the snippet not necessarily why, but document _when_ to include/exclude `pkgname::`  for the unit test guidance?

**Review by bms63 — APPROVED** [review]
LGTM!
