### PR TITLE
Closes #101 increase test coverage compat friendly type r@devel

### LINKED ISSUE #101: General Issue: Increase test coverage for `compat_friendly_type.R`
### Background Information

We need to increase test coverage for our functions. The below screenshot has the function and gap in test coverage that we need to write additional unit tests for `compat_friendly_type.R`.  

Unsure if this is a good one for us to tackle.  @thomas-neitmann @bundfussr.  I'm still not entirely clear why we import these functions (3.6?) .  But should we build some tests around these gaps?

image

### Definition of Done

New tests written that covers the red gap area for `compat_friendly_type.R`

Use devtools::test_coverage() to reproduce the report

### PR DESCRIPTION
**Pull request by zdz2101**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page.
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging.
- [x] Address all merge conflicts and resolve appropriately.
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

File: tests/testthat/test-compat_friendly_type.R [hunk 1]
```diff
@@ -1,11 +1,12 @@
...
 ## Test 1: friendly_type_of() supports objects ----
-test_that("compat_friendly_type Test 1: friendly_type_of() supports objects", {
+test_that("friendly_type_of Test 1: friendly_type_of() supports objects", {
   expect_equal(friendly_type_of(mtcars), "a <data.frame> object")
   expect_equal(friendly_type_of(quo(1)), "a <quosure> object")
 })
 
 ## Test 2: friendly_type_of() supports matrices and arrays (#141) ----
-test_that("compat_friendly_type Test 2: friendly_type_of() supports matrices and arrays (#141)", {
+test_that("friendly_type_of Test 2: friendly_type_of() supports matrices and arrays (#141)", {
```
Comment (bms63) [inline tests/testthat/test-compat_friendly_type.R:9]: Do you know what this #141 is?  This might be from the rlang package.  I copied some of these tests over from them

**Review by bms63 — APPROVED** [review]
Thanks Zelos!!

**Comment by bms63** [comment]
Do you think we should make any of these notes into ISsues?

**Comment by zdz2101** [comment]
Maybe not necessarily as its own stand-alone issue for now, perhaps down the line if we do another "Increase unit test-coverage of xxx.R" refresher it can be a part of that. Think we have more things to worry about if people try and feed these exotic function arguments into admiral
